/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import javax.swing.JOptionPane;
import com.mycompany.tugasakhir.*;
import java.util.ArrayList;

/**
 *
 * @author Lenovo X380 Yoga
 */
public class Mart extends javax.swing.JFrame {
    static boolean rotiAstaghfirullah;
    static boolean rotiCapek;
    static boolean rotiSbubu;
    static boolean keripikGapapa;
    static boolean keripikWaduh;
    
    /**
     * Creates new form Mart
     */
    public Mart() {
        initComponents();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField1_namaPegawai = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2_kodePegawai = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3_posisiPegawai = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cbras_RotiAstaghfirullah = new javax.swing.JCheckBox();
        cbrs_rotisbubu = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jmlras = new javax.swing.JTextField();
        jmlrc = new javax.swing.JTextField();
        jmlrs = new javax.swing.JTextField();
        cbrc_rotiCapek = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jButton2_Reset = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        cbras1_keripikwaduh = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        jmlkwdh = new javax.swing.JTextField();
        jmlkg = new javax.swing.JTextField();
        cbrc1_keripikGapapa = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        txtlv = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtcal = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtcash = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1_nota = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(102, 16, 10));
        jPanel5.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 187, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pegawai");
        jPanel5.add(jLabel1);
        jLabel1.setBounds(27, 29, 93, 32);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jSeparator1);
        jSeparator1.setBounds(17, 73, 215, 10);

        jTextField1_namaPegawai.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1_namaPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_namaPegawaiActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField1_namaPegawai);
        jTextField1_namaPegawai.setBounds(10, 160, 215, 30);

        jLabel2.setBackground(new java.awt.Color(255, 187, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama");
        jPanel5.add(jLabel2);
        jLabel2.setBounds(10, 140, 60, 16);

        jLabel3.setBackground(new java.awt.Color(255, 187, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kode Pegawai");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(10, 210, 120, 16);

        jTextField2_kodePegawai.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2_kodePegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_kodePegawaiActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField2_kodePegawai);
        jTextField2_kodePegawai.setBounds(10, 230, 215, 30);

        jLabel4.setBackground(new java.awt.Color(255, 187, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Posisi/Jabatan");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(10, 280, 110, 16);

        jTextField3_posisiPegawai.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3_posisiPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3_posisiPegawaiActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField3_posisiPegawai);
        jTextField3_posisiPegawai.setBounds(10, 300, 215, 30);

        jPanel3.setBackground(new java.awt.Color(250, 205, 160));
        jPanel3.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(191, 27, 15));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Laman Pemesanan");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 16, 529, 60);

        jPanel1.setBackground(new java.awt.Color(250, 205, 160));
        jPanel1.setForeground(new java.awt.Color(0, 51, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 16, 10));
        jLabel6.setText("Nama");

        cbras_RotiAstaghfirullah.setBackground(new java.awt.Color(250, 205, 160));
        cbras_RotiAstaghfirullah.setForeground(new java.awt.Color(102, 16, 10));
        cbras_RotiAstaghfirullah.setText("Roti Astagfirullah");
        cbras_RotiAstaghfirullah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbras_RotiAstaghfirullahActionPerformed(evt);
            }
        });

        cbrs_rotisbubu.setForeground(new java.awt.Color(102, 16, 10));
        cbrs_rotisbubu.setText("Roti Sbubu");
        cbrs_rotisbubu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbrs_rotisbubuActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 16, 10));
        jLabel7.setText("Qty");

        jmlras.setBackground(new java.awt.Color(255, 255, 255));
        jmlras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlrasActionPerformed(evt);
            }
        });

        jmlrc.setBackground(new java.awt.Color(255, 255, 255));

        jmlrs.setBackground(new java.awt.Color(255, 255, 255));

        cbrc_rotiCapek.setForeground(new java.awt.Color(102, 16, 10));
        cbrc_rotiCapek.setText("Roti Capek");
        cbrc_rotiCapek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbrc_rotiCapekActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Roti");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbrs_rotisbubu, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jmlrs, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbrc_rotiCapek, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jmlrc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(cbras_RotiAstaghfirullah))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(jmlras, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel9)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbras_RotiAstaghfirullah)
                    .addComponent(jmlras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jmlrc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbrc_rotiCapek))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbrs_rotisbubu)
                    .addComponent(jmlrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1);
        jPanel1.setBounds(0, 20, 241, 270);

        jButton2_Reset.setText("Reset");
        jButton2_Reset.setBorderPainted(false);
        jButton2_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_ResetActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2_Reset);
        jButton2_Reset.setBounds(440, 390, 72, 32);
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(20, 310, 500, 30);

        jPanel2.setBackground(new java.awt.Color(250, 205, 160));
        jPanel2.setForeground(new java.awt.Color(0, 51, 255));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 16, 10));
        jLabel15.setText("Nama");

        cbras1_keripikwaduh.setBackground(new java.awt.Color(250, 205, 160));
        cbras1_keripikwaduh.setForeground(new java.awt.Color(102, 16, 10));
        cbras1_keripikwaduh.setText("Keripik Waduh");
        cbras1_keripikwaduh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbras1_keripikwaduhActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 16, 10));
        jLabel16.setText("Qty");

        jmlkwdh.setBackground(new java.awt.Color(255, 255, 255));
        jmlkwdh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlkwdhActionPerformed(evt);
            }
        });

        jmlkg.setBackground(new java.awt.Color(255, 255, 255));
        jmlkg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlkgActionPerformed(evt);
            }
        });

        cbrc1_keripikGapapa.setForeground(new java.awt.Color(102, 16, 10));
        cbrc1_keripikGapapa.setText("Keripik Gapapa");
        cbrc1_keripikGapapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbrc1_keripikGapapaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 16, 10));
        jLabel11.setText("Level Pedas (khusus keripik waduh)");

        txtlv.setBackground(new java.awt.Color(255, 255, 255));
        txtlv.setText(" ");
        txtlv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlvActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Keripik");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbrc1_keripikGapapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jmlkg, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbras1_keripikwaduh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jmlkwdh, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtlv, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel8)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbras1_keripikwaduh)
                    .addComponent(jmlkwdh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jmlkg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbrc1_keripikGapapa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtlv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2);
        jPanel2.setBounds(260, 20, 260, 290);

        txtcal.setBackground(new java.awt.Color(102, 16, 10));
        txtcal.setForeground(new java.awt.Color(255, 255, 255));
        txtcal.setText("Hitung");
        txtcal.setBorderPainted(false);
        txtcal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcalActionPerformed(evt);
            }
        });
        jPanel3.add(txtcal);
        txtcal.setBounds(360, 390, 72, 32);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 16, 10));
        jLabel17.setText("Total :");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(260, 320, 70, 20);

        txttotal.setBackground(new java.awt.Color(255, 255, 255));
        txttotal.setForeground(new java.awt.Color(0, 0, 0));
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });
        jPanel3.add(txttotal);
        txttotal.setBounds(320, 320, 180, 22);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 16, 10));
        jLabel13.setText("Cash :");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(260, 350, 50, 20);

        txtcash.setBackground(new java.awt.Color(255, 255, 255));
        txtcash.setForeground(new java.awt.Color(0, 0, 0));
        txtcash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcashActionPerformed(evt);
            }
        });
        jPanel3.add(txtcash);
        txtcash.setBounds(320, 350, 180, 22);

        jPanel5.add(jPanel3);
        jPanel3.setBounds(250, 0, 529, 430);

        jLabel10.setBackground(new java.awt.Color(255, 166, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 166, 0));
        jLabel10.setText("Ini Nota");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(890, 30, 100, 32);

        jTextArea1_nota.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1_nota.setColumns(20);
        jTextArea1_nota.setRows(5);
        jScrollPane1.setViewportView(jTextArea1_nota);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(790, 80, 310, 340);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1107, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1_namaPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_namaPegawaiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1_namaPegawaiActionPerformed

    private void jTextField2_kodePegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_kodePegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_kodePegawaiActionPerformed

    private void jTextField3_posisiPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3_posisiPegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3_posisiPegawaiActionPerformed

    private void jButton2_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_ResetActionPerformed
        // TODO add your handling code here:
        jTextField1_namaPegawai.setText(null);
        jTextField2_kodePegawai.setText(null);
        jTextField3_posisiPegawai.setText(null);
        jmlras.setText(null);
        jmlrc.setText(null);
        jmlrs.setText(null);
        jmlkwdh.setText(null);
        jmlkg.setText(null);
        jTextArea1_nota.setText(null);
        cbras_RotiAstaghfirullah.setSelected(false);
        cbrc_rotiCapek.setSelected(false);
        cbrs_rotisbubu.setSelected(false);
        cbras1_keripikwaduh.setSelected(false);
        cbrc1_keripikGapapa.setSelected(false);
    }//GEN-LAST:event_jButton2_ResetActionPerformed

    private void cbras_RotiAstaghfirullahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbras_RotiAstaghfirullahActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbras_RotiAstaghfirullahActionPerformed

    private void jmlrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlrasActionPerformed

    private void cbrc_rotiCapekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbrc_rotiCapekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbrc_rotiCapekActionPerformed

    private void txtlvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlvActionPerformed

    private void cbrc1_keripikGapapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbrc1_keripikGapapaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbrc1_keripikGapapaActionPerformed

    private void jmlkwdhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlkwdhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlkwdhActionPerformed

    private void cbras1_keripikwaduhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbras1_keripikwaduhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbras1_keripikwaduhActionPerformed

    private void txtcalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcalActionPerformed
        // TODO add your handling code here:
        String tampil = " ";
        double pembayaran = Double.parseDouble(txtcash.getText());
        double total = 0;
        
        String namaP = jTextField1_namaPegawai.getText();
        String kodeP = jTextField2_kodePegawai.getText();
        String posisiP = jTextField3_posisiPegawai.getText();
       
        com.mycompany.tugasakhir.Mart myMart = new com.mycompany.tugasakhir.Mart();
        Pegawai pegawai1 = new Pegawai(namaP, kodeP, posisiP);
        
        if (cbras_RotiAstaghfirullah.isSelected()){
            String namaRAS = "Roti Astaghfirullah";
            double hargaRAS = 5000;
            String kodeRAS = "RAS001";
            int jumlahRAS = 1000;
            String tglRAS = "20122033";
            int beliRAS = Integer.parseInt(jmlras.getText());
            RotiAstaghfirullah rotiAs = new RotiAstaghfirullah(namaRAS,hargaRAS,kodeRAS,jumlahRAS,tglRAS);
            myMart.addProduct(rotiAs);
            rotiAs.jual(beliRAS);
            tampil += rotiAs.getId() + " " +  rotiAs.getNama() + " " + rotiAs.getPrice() + " x " + beliRAS + " = " + beliRAS*rotiAs.getPrice() + "\n";
            total += beliRAS*rotiAs.getPrice();
            
        } if (cbrc_rotiCapek.isSelected()){
            String namaRC = "Roti Capek";
            double hargaRC = 6000;
            String kodeRC = "RC002";
            int jumlahRC = 1000;
            String tglRC = "20122033";
            int beliRC = Integer.parseInt(jmlrc.getText());
            RotiCapek rotiC = new RotiCapek(namaRC,hargaRC,kodeRC,jumlahRC,tglRC);
            myMart.addProduct(rotiC);
            rotiC.jual(beliRC);
            tampil += rotiC.getId() + " " +  rotiC.getNama() + " " + rotiC.getPrice() + " x " + beliRC + " = " + beliRC*rotiC.getPrice() + "\n";
            total += beliRC*rotiC.getPrice();
            
        } if (cbrs_rotisbubu.isSelected()){
            String namaRS = "Roti Sbubu";
            double hargaRS = 4500;
            String kodeRS = "RS003";
            int jumlahRS = 1000;
            String tglRS = "20122033";
            int beliRS = Integer.parseInt(jmlrs.getText());
            RotiSbubu rotiS = new RotiSbubu(namaRS,hargaRS,kodeRS,jumlahRS,tglRS);
            myMart.addProduct(rotiS);
            rotiS.jual(beliRS);
            tampil += rotiS.getId() + " " +  rotiS.getNama() + " " + rotiS.getPrice() + " x " + beliRS + " = " + beliRS*rotiS.getPrice() + "\n";
            total += beliRS*rotiS.getPrice();
            
        } if (cbras1_keripikwaduh.isSelected()){
            String namaKW = "Keripik Waduh";
            double hargaKW = 9000;
            String kodeKW = "KW011";
            int jumlahKW = 1000;
            int hotLv = Integer.parseInt(txtlv.getText());
            int beliKW = Integer.parseInt(jmlkwdh.getText());
            KeripikWaduh keripikW = new KeripikWaduh(namaKW,hargaKW,kodeKW,jumlahKW,hotLv);
            myMart.addProduct(keripikW);
            keripikW.jual(beliKW);
            tampil += keripikW.getId() + " " +  keripikW.getNama() + " " + keripikW.getPrice() + " x " + beliKW + " = " + beliKW*keripikW.getPrice() + "\n";
            total += beliKW*keripikW.getPrice();
            
        } if (cbrc1_keripikGapapa.isSelected()){
            String namaKG = "Keripik Gapapa";
            double hargaKG = 7000;
            String kodeKG = "KG012";
            int jumlahKG = 1000;
            int beliKG = Integer.parseInt(jmlkg.getText());
            KeripikGapapa keripikG = new KeripikGapapa(namaKG,hargaKG,kodeKG,jumlahKG);
            myMart.addProduct(keripikG);
            keripikG.jual(beliKG);
            tampil += keripikG.getId() + " " +  keripikG.getNama() + " " + keripikG.getPrice() + " x " + beliKG + " = " + beliKG*keripikG.getPrice() + "\n";
            total += beliKG*keripikG.getPrice();
        }
        txttotal.setText(""+total);

        jTextArea1_nota.setText("----------Toko Snack Normal----------" + "\n" +
                                pegawai1.getNama() + " / " + pegawai1.getidPegawai() + " / " + pegawai1.getPosisi() + "\n" +
                                "====================================" + "\n" +
                                tampil + "\n" +
                                "====================================" + "\n" +
                                "Total bayar    = " + "Rp." + total + "\n" +
                                "Cash           = " + "Rp." + pembayaran + "\n" +
                                "Kembali        = " + "Rp." + Math.abs(pembayaran - total) + "\n" + "\n" +
                                "TERIMA KASIH" + "\n"
                                + "BESOK DATENG LAGI YA!!! KAMI MAKSA!");
        
        
        
    }//GEN-LAST:event_txtcalActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void cbrs_rotisbubuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbrs_rotisbubuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbrs_rotisbubuActionPerformed

    private void jmlkgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlkgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlkgActionPerformed

    private void txtcashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcashActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Mart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbras1_keripikwaduh;
    private javax.swing.JCheckBox cbras_RotiAstaghfirullah;
    private javax.swing.JCheckBox cbrc1_keripikGapapa;
    private javax.swing.JCheckBox cbrc_rotiCapek;
    private javax.swing.JCheckBox cbrs_rotisbubu;
    private javax.swing.JButton jButton2_Reset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1_nota;
    private javax.swing.JTextField jTextField1_namaPegawai;
    private javax.swing.JTextField jTextField2_kodePegawai;
    private javax.swing.JTextField jTextField3_posisiPegawai;
    private javax.swing.JTextField jmlkg;
    private javax.swing.JTextField jmlkwdh;
    private javax.swing.JTextField jmlras;
    private javax.swing.JTextField jmlrc;
    private javax.swing.JTextField jmlrs;
    private javax.swing.JButton txtcal;
    private javax.swing.JTextField txtcash;
    private javax.swing.JTextField txtlv;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
